---
title: "Figures for multiple blood-feeding project"
author: |
    | Kyle J.-M. Dahlin, Michael Robert, Lauren Childs
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    keep_tex: yes
    extra_dependencies: ["float"]
    includes:
      in_header: header.tex
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "doc") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, cache = FALSE, warning = FALSE, fig.pos = "H",
  out.extra = ""
)
# Load Libraries----------------------------------------------------------------
library(tidyverse)
library(latex2exp)
library(reshape2)
library(cowplot)
library(viridis)
library(RColorBrewer) # for colorblind friendly color palettes
library(MetBrewer) # for colorblind friendly color palettes
library(cols4all) # for colorblind friendly color palettes
library(here)
library(lemon)
library(see) # for half-violin plots
library(zplyr) # devtools::install_github("burchill/zplyr") from https://github.com/burchill/zplyr/ # only needed for placing text using absolute coordinates in contdact comparison figure

# Plot settings ----

# Set theme
# theme_set(theme_minimal(10))

# Label functions:
appender_variable <- function(string) {
  unname(TeX(paste("$\\variable = $", string)))
}

# Helper function: place legends in empty facets of plot grids
# Code by: Artem Sokolov, found here: https://stackoverflow.com/questions/54438495/shift-legend-into-empty-facets-of-a-faceted-plot-in-ggplot2
shift_legend <- function(p) {
  pnls <- cowplot::plot_to_gtable(p) %>%
    gtable::gtable_filter("panel") %>%
    with(setNames(grobs, layout$name)) %>%
    purrr::keep(~ identical(.x, zeroGrob()))
  
  if (length(pnls) == 0) stop("No empty facets in the plot")
  
  lemon::reposition_legend(p, "center", panel = names(pnls))
}

# Load required data ----
eps <- .Machine$double.eps

# Run 'simulate_CTMC.R' and 'get_outputs.R' first to produce simulated data and
# fits for distributions

all_dists <- read_rds("data/fit_dists.rds") %>% 
  rbind(read_rds("data/mech_dists.rds"))


# Configure data sets for plotting ----


```

```{r calc-R0}

# # Load in biting rate parameters (should be same as all_dists)
# bite_params <- tibble(A = mats, alpha = alphas, dims = dims, class = NA)
bite_params = all_dists

# Load in other parameters and functions
source("code/get_outputs.R")
# This outputs a data frame "full_df" that contains all the parameters needed to calculate R0

# Calculate equilibrium quantities
calc_df = eq_func(full_df)

in_df = calc_df

out_df = repnum_func(in_df)

out_df = veccap_func(out_df) %>% 
  mutate(V_tot = B_star + V_star) %>% 
  mutate(class_label = factor(case_when(
    class == "coxian" ~ "Phenomenological",
    class == "general" ~ "Empirical",
    class == "Mechanistic" ~ class
  ), levels = c("Empirical", "Phenomenological", "Mechanistic"))
  )
```

```{r fig-1_R0_compare, dev = c('pdf','svg', 'png'), out.width='100%', fig.align='center', fig.height=9, fig.width=16, fig.align='center', fig.cap='\\label{fig:1} Comparing R0 distributions.'}

# Violin plot of distributions of R0 for empirically, phenomenologically, and mechanistically
# fitted distributions

# Choose dimension for now
plot_dim = 4

# Set up data frame for plotting
plot_df <- out_df %>% 
  filter(dimension == plot_dim,
         type == "logistic") %>% 
  # filter(tau < 1 & tau > 0) %>% 
  # filter(class != "Mechanistic") %>%
  # filter(R0 > 0) %>% 
  # filter(R0 < 100) %>%
  select(A, alpha, dimension, class_label, R, tau, R0, B_star, veccap) 


  
R0_compare_plot <- plot_df %>% 
  ggplot(aes(x = class_label, y = R0)) +
  # geom_boxplot() +
  geom_violin(scale = "width",
              draw_quantiles = c(0.025, 0.5, 0.975),
              size = 1) +
  geom_jitter(width = 0.2, color = "blue", alpha = 0.5) +
  geom_hline(yintercept = 1, color = "red", size = 1) +
  xlab("") +
  ylab(TeX("Basic reproduction number (R0)")) +
  coord_cartesian(ylim = c(0,15)) +
  theme_cowplot(24)

R0_compare_plot

ggsave("figures/R0_compare.png", plot = R0_compare_plot,
       width = 16, height = 9)

```

```{r fig-1_V_compare, dev = c('pdf','svg', 'png'), out.width='100%', fig.align='center', fig.height=9, fig.width=16, fig.align='center', fig.cap='\\label{fig:2} Comparing mosquito population densities.'}

# Choose dimension for now
plot_dim = 4

# Set up data frame for plotting
plot_df <- out_df %>% 
  filter(dimension == plot_dim,
         type == "logistic") %>% 
  # filter(tau < 1 & tau > 0) %>% 
  # filter(class != "Mechanistic") %>%
  # filter(R0 > 0) %>% 
  # filter(R0 < 100) %>%
  select(A, alpha, dimension, class_label, R, tau, R0, B_star, V_tot)
  
V_compare_plot <- plot_df %>% 
  ggplot(aes(x = class_label, y = V_tot)) +
  # geom_boxplot() +
  geom_violin(scale = "width",
              draw_quantiles = c(0.025, 0.5, 0.975),
              size = 1) +
  geom_jitter(width = 0.2, color = "blue", alpha = 0.5) +
  xlab("") +
  ylab(TeX("Vector population density")) +
  # coord_cartesian(ylim = c(0,15)) +
  theme_cowplot(24)

V_compare_plot

ggsave("figures/V_compare.png", plot = V_compare_plot,
       width = 16, height = 9)

```

```{r fig-1_V_compare, dev = c('pdf','svg', 'png'), out.width='100%', fig.align='center', fig.height=9, fig.width=16, fig.align='center', fig.cap='\\label{fig:2} Comparing mosquito population densities.'}

# Choose dimension for now
plot_dim = 4

# Set up data frame for plotting
plot_df <- out_df %>% 
  filter(dimension == plot_dim,
         type == "logistic") %>% 
  # filter(tau < 1 & tau > 0) %>% 
  # filter(class != "Mechanistic") %>%
  # filter(R0 > 0) %>% 
  # filter(R0 < 100) %>%
  select(A, alpha, dimension, class_label, R, tau, R0, B_star, veccap) 

veccap_compare_plot <- plot_df %>% 
  ggplot(aes(x = class_label, y = veccap)) +
  # geom_boxplot() +
  geom_violin(scale = "width",
              draw_quantiles = c(0.025, 0.5, 0.975),
              size = 1) +
  geom_jitter(width = 0.2, color = "blue", alpha = 0.5) +
  xlab("") +
  ylab(TeX("Vectorial capacity")) +
  # coord_cartesian(ylim = c(0,15)) +
  theme_cowplot(24)

veccap_compare_plot

ggsave("figures/veccap_compare.png", plot = veccap_compare_plot,
       width = 16, height = 9)

```

```{r R0_t_tests}

test_data = select(plot_df, class, R0) %>% 
  filter(class != "Mechanistic")
t.test(R0~class, var.equal = T, data = test_data)

test_data = select(plot_df, class, R0) %>% 
  filter(class != "coxian")
t.test(R0~class, var.equal = T, data = test_data)


test_data = select(plot_df, class, R0) %>% 
  filter(class != "general")
t.test(R0~class, var.equal = T, data = test_data)

```

```{r Vtot_t_tests}

test_data = select(out_df, class, V_tot) %>% 
  filter(class != "Mechanistic")
t.test(V_tot~class, var.equal = T, data = test_data)

test_data = select(out_df, class, V_tot) %>% 
  filter(class != "coxian")
t.test(V_tot~class, var.equal = T, data = test_data)


test_data = select(out_df, class, V_tot) %>% 
  filter(class != "general")
t.test(V_tot~class, var.equal = T, data = test_data)

```